library(ScottKnottESD)
library(ggplot2)
library(gridExtra)
setwd("~/Research/mining-ownership/Part2")
df_features <- read.csv("rq5_explanation.csv")

# RQ5: Should code ownership approximations be used to explain why a file is predicted as defective?

# RQ5.1) How many correctly predicted defective files that code ownership approximations can be used to explain its predictions as defective
percentage <- NULL
for(project in unique(df_features$j)){
  data <- df_features[df_features$j == project, ]
  total_tp_files <- length(unique(data$filename))
  p <- length(unique(data[data$left %in% c("OWN_COMMIT","OWN_LINE"),c("filename")]))
  percentage <- c(percentage, p/total_tp_files)
}
percentage <- data.frame(project=unique(df_features$j), percentage)
p1 <- ggplot(percentage, aes(y=percentage)) + geom_boxplot() + scale_y_continuous(limits = c(0,1), breaks=c(0,0.2,0.4,0.6,0.8,1.0)) + scale_x_discrete(limits = c("")) + labs(y="#Correctly Predicted Defective Files", x = "") + ggtitle("RQ5.1")

# RQ5.2) What are and If the supporting scores of commit-based code ownership approximation are statistically higher than the supporting scores of line-based code ownership approximation  
data <- df_features[df_features$left %in% c("OWN_COMMIT","OWN_LINE"), c("left","score")]
data <- data[data$score > 0,]
data$left <- factor(data$left, level=unique(data$left))
p2 <- ggplot(data, aes(x=left,y=score)) + geom_boxplot() + scale_y_continuous(limits = c(0,0.5)) + labs(y="LIME's Supporting Scores", x = "")+ ggtitle("RQ5.2")

wilcox.test(data[data$left == "OWN_COMMIT","score"],data[data$left == "OWN_LINE","score"])
cliff.delta(data[data$left == "OWN_COMMIT","score"],data[data$left == "OWN_LINE","score"])

# RQ5.3) The number of LIME's decision rules that satisfy the actual values of code ownership features for correctly predicted defective files in the testing data  (i.e., a release $j$)
data <- df_features[df_features$left %in% c("OWN_COMMIT","OWN_LINE"),]
data <- table(data[data$condition %in% c('>','>=') & data$X_test >= data$right,"j"])/table(data[,"j"])
data <- melt(data)
p3 <- ggplot(data, aes(y=value)) + geom_boxplot() + scale_y_continuous(limits = c(0,1), breaks=c(0,0.2,0.4,0.6,0.8,1.0)) + scale_x_discrete(limits = c("")) + labs(y="#LIME's Decision Rules", x = "") + ggtitle("RQ5.3")

pdf("RQ5-score.pdf", width = 5, height = 3.5)
grid.arrange(p1, p2, p3, ncol=3, widths = c(1,2,1))
dev.off()


# RQ6: How applicable is the quality improvement plan based on code ownership approximation?
# X% of quality improvement plans generated by LIME are applicable to guide developers to minimize the risks of having defects.

# Look at BUGGY in j => CLEAN in k
data <- df_features[df_features$left %in% c("OWN_COMMIT") & df_features$y_test == 'True' & df_features$y_validate == 'False',]

# Check how many defective files that whose improvement plans are satisfied 
p1 = table(data[data$condition %in% c('>','>=') & data$right <= data$X_validate,"j"])/table(data[,"j"])
p2 = table(data[data$condition %in% c('<','<=') & data$right >= data$X_validate,"j"])/table(data[,"j"])
data <- melt(p1+p2)

ggplot(data, aes(x=Var1, y=value)) + geom_bar(stat = "identity") + labs(y="#QA Plans", x = "") + theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("RQ6-plans.pdf", width = 5, height = 3.5)
